genre_fashion = {
    "pop": ["stylish jacket", "skinny jeans", "sneakers"],
    "rock": ["leather jacket", "ripped jeans", "band t-shirt"],
    "hip-hop": ["hoodie", "baggy pants", "high-top sneakers"],
    "electronic": ["cyberpunk outfit", "neon accessories", "LED shoes"],
    "jazz": ["blazer", "slacks", "loafers"],
    "classical": ["formal suit", "bowtie", "dress shoes"],
    "reggae": ["rasta hat", "tie-dye shirt", "flip-flops"],
    "country": ["cowboy hat", "plaid shirt", "cowboy boots"],
    "blues": ["fedora", "vest", "wingtip shoes"],
    "metal": ["black leather jacket", "black jeans", "combat boots"],
    "indie": ["flannel shirt", "distressed jeans", "vintage sneakers"],
    "rap": ["streetwear hoodie", "cargo pants", "hightop sneakers"],
    "soul": ["retro dress", "platform shoes", "big sunglasses"],
    "punk": ["punk leather jacket", "ripped skinny jeans", "combat boots"],
    "folk": ["bohemian dress", "suede boots", "headband"],
    "disco": ["sequin dress", "disco ball earrings", "platform heels"],
    "funk": ["colorful bell-bottom pants", "afro wig", "platform shoes"],
    "r&b": ["silk blouse", "high-waisted pants", "stilettos"],
    "alternative": ["grunge flannel", "distressed jeans", "combat boots"],
    "techno": ["rave outfit", "goggles", "glowstick bracelets"],
    "punk-rock": ["studded leather jacket", "skinny jeans", "biker boots"],
    "ska": ["ska band t-shirt", "checkered pants", "skate shoes"],
    "latin": ["salsa dress", "Latin dance shoes", "statement earrings"],
    "bluegrass": ["western shirt", "denim overalls", "cowboy boots"],
    "opera": ["formal gown", "opera gloves", "pearl necklace"],
    "trap": ["streetwear hoodie", "track pants", "sneaker boots"],
    "house": ["rave outfit", "glow-in-the-dark accessories", "sneakers"],
    "acoustic": ["bohemian dress", "fringe boots", "flower crown"],
    "j-pop": ["kawaii outfit", "platform shoes", "cute accessories"],
    "k-pop": ["K-pop idol outfit", "colorful sneakers", "statement jewelry"],
    "rap-rock": ["urban streetwear", "ripped jeans", "high-top sneakers"],
    "grunge-rock": ["grunge flannel", "distressed jeans", "combat boots"],
    "punk-pop": ["punk-inspired outfit", "edgy accessories", "platform boots"],
    "symphony": ["formal evening gown", "diamond jewelry", "elegant heels"],
    "ambient": ["minimalist attire", "neutral colors", "comfortable flats"],
    "trance": ["psychedelic clothing", "trance-themed accessories", "LED shoes"],
    "samba": ["samba costume", "feather headdress", "samba shoes"],
    "flamenco": ["flamenco dress", "flamenco fan", "flamenco shoes"],
    "reggaeton": ["streetwear with a Latin flair", "urban sneakers", "gold jewelry"],
    "chill-out": ["relaxed and casual wear", "earth tones", "slip-on shoes"],
    "dubstep": ["rave-inspired clothing", "neon accessories", "hightop sneakers"],
    "trap-metal": ["metal-inspired streetwear", "distressed jeans", "combat boots"],
    "emo": ["emo-style attire", "skinny jeans", "converse sneakers"],
    "vaporwave": ["vaporwave aesthetic clothing", "retro sneakers", "oversized sunglasses"],
    "lo-fi": ["cozy and comfortable attire", "beanie hat", "vintage sneakers"],
    # Additional genres
    "gospel": ["choir robe", "simple dress", "formal shoes"],
    "world": ["cultural attire", "artisan jewelry", "comfortable sandals"],
    "new age": ["flowing garments", "crystal jewelry", "barefoot sandals"],
    "swing": ["vintage dress", "wingtip shoes", "fedora"],
    "electropop": ["futuristic outfit", "holographic accessories", "light-up sneakers"],
    "hardcore": ["band t-shirt", "cargo shorts", "work boots"],
    "drum and bass": ["sporty attire", "baseball cap", "trainers"],
    "progressive": ["artsy outfit", "unconventional accessories", "unique shoes"],
    "anime": ["anime-themed clothing", "cute accessories", "colorful sneakers"]
}
